// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Canteen.DataAccess
{
    public partial class LunchMenu
    {
        public LunchMenu()
        {
            EmployeeLunches = new HashSet<EmployeeLunch>();
        }

        public int LunchMenuId { get; set; }
        public short Number { get; set; }
        public short Year { get; set; }
        public int? MondayItemId { get; set; }
        public int? TuesdayItemId { get; set; }
        public int? WednesdayItemId { get; set; }
        public int? ThursdayItemId { get; set; }
        public int? FridayItemId { get; set; }
        public int? MondayLunchCancellationId { get; set; }
        public int? TuesdayLunchCancellationId { get; set; }
        public int? WednesdayLunchCancellationId { get; set; }
        public int? ThursdayLunchCancellationId { get; set; }
        public int? FridayLunchCancellationId { get; set; }

        public virtual Item? FridayItem { get; set; }
        public virtual LunchCancellation? FridayLunchCancellation { get; set; }
        public virtual Item? MondayItem { get; set; }
        public virtual LunchCancellation? MondayLunchCancellation { get; set; }
        public virtual Item? ThursdayItem { get; set; }
        public virtual LunchCancellation? ThursdayLunchCancellation { get; set; }
        public virtual Item? TuesdayItem { get; set; }
        public virtual LunchCancellation? TuesdayLunchCancellation { get; set; }
        public virtual Item? WednesdayItem { get; set; }
        public virtual LunchCancellation? WednesdayLunchCancellation { get; set; }
        public virtual Week Week { get; set; } = null!;
        public virtual ICollection<EmployeeLunch> EmployeeLunches { get; set; }
    }
}